Fix error
Fix error caused by querying non-standard ERC20 contracts without Dec…imal function

Error: (code: -32000, message: contract creation code storage out of gas, data: e.g. 0xc0ca776fe52)
Example: 0xc0ca776fe52eC92b1D5603cAadf148DbD8C22a80